### ISSUE TITLE
Consolidate lists

### ISSUE THREAD

**Issue by pallebone** [Esox-Lucius/PiHoleblocklists#1]
Hello, 

Thank you for this work. It is very interesting to me and I would like to make use of it.

Is there any way to consolidate all the separate lists into 1 single list to add to pihole rather than adding what looks to be 50-100 separate entries? Or is this something that can be setup somehow?

Kind regards
Peter

**Comment by pallebone** [comment]
Saw you updated the lists... just wondering if you had a chance to check my query out?

**Comment by Esox-Lucius** [comment]
Hi Peter, and sorry for not answering faster, but I have been busy with other projects. 

I think there must be a way to compile it all into 1 single list. The reason I have them separate is that there are different types of threats, and some need more maintenance than others and also to make it more streamlined for myself and how I work. 

The lists here are at this point only for testing, and to keep it simple when adding/removing lists to the systems I play around with I chose to have each threat on its own separate list. 

I'm no super user as to Github and coding yet, so can't say how it should be done.

**Comment by pallebone** [comment]
No problem thank you
