### ISSUE TITLE
Wrong page on list?

### ISSUE THREAD

**Issue by criwe** [Esox-Lucius/PiHoleblocklists#3]
Hi!
You have seitzdruck.com an the list.
I had contact to the webmaster, we didn´t find any maleware on that site.
Could it be a mistake? Or do you have any further informations?
Thanks!

**Comment by Esox-Lucius** [comment]
Hi criwe, It might have been a false positive, and I have now removed seitzdruck.com from list: https://raw.githubusercontent.com/Esox-Lucius/PiHoleblocklists/main/Malware%20-%20Ransomware%20Sodinokibi

**Comment by criwe** [comment]
Thanks!
