### ISSUE TITLE
Remove covid-19.samsam123.tk from the blocklist

### ISSUE THREAD

**Issue by samleong123** [Esox-Lucius/PiHoleblocklists#6]
Hi , this website isn't a spam or malicious site.
It was proxied to http://covid-19.moh.gov.my , Malaysia COVID-19 Official Website 
The purpose of this proxied site is they didn't intend to provide HTTPS protocol in 2021.
That's why i provided a proxied site that enabled HTTPS support and also Cloudflare CDN.
Request to remove covid-19.samsam123.tk from the blocklist.
Regards ,
Sam

**Comment by Esox-Lucius** [comment]
Hi Sam and thanks for the feedback. I do apologize for the long awaited answer, but have been busy with other things. I have removed covid-19.samsam123.tk from list: https://raw.githubusercontent.com/Esox-Lucius/PiHoleblocklists/main/Covid-19%20Related%20Domains%20(SPAM)
