### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [Esox-Lucius/PiHoleblocklists#7]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/Esox-Lucius/PiHoleblocklists/main/Malware%20-%20Crypto%20Mining%20Pool%20Hosts). Thanks!

**Comment by Esox-Lucius** [comment]
I apologies for the long awaited reply. I have removed BitCanna from that list. Thanks for the heads up!
